// Icon registry — generated by scripts/extract-state-pages.mjs's output.
// Regenerate with: node scripts/gen-icon-registry.mjs
//
// Page content lives in the database, where an icon can only be stored as a NAME
// ("TimerIcon"), not as a component reference. This maps those names back to
// components for the renderer.
//
// Deep single imports ("@mui/icons-material/Timer") rather than named imports off
// the package root: the root re-exports several thousand icons, and pulling the
// map in from there defeats tree-shaking and lands the whole set in the bundle.
//
// 72 icons, every one of them actually used by an extracted page.

import AccessTimeFilledIcon from "@mui/icons-material/AccessTimeFilled";
import AccessTimeIcon from "@mui/icons-material/AccessTime";
import AccountBalanceIcon from "@mui/icons-material/AccountBalance";
import AccountBalanceWalletIcon from "@mui/icons-material/AccountBalanceWallet";
import AdsClickIcon from "@mui/icons-material/AdsClick";
import ArticleIcon from "@mui/icons-material/Article";
import AssessmentIcon from "@mui/icons-material/Assessment";
import AssignmentIcon from "@mui/icons-material/Assignment";
import BarChartIcon from "@mui/icons-material/BarChart";
import BuildIcon from "@mui/icons-material/Build";
import BusinessIcon from "@mui/icons-material/Business";
import CallIcon from "@mui/icons-material/Call";
import CenterFocusStrongIcon from "@mui/icons-material/CenterFocusStrong";
import CheckCircleIcon from "@mui/icons-material/CheckCircle";
import CleaningServicesIcon from "@mui/icons-material/CleaningServices";
import CloudSyncIcon from "@mui/icons-material/CloudSync";
import CloudUploadIcon from "@mui/icons-material/CloudUpload";
import ContactMailIcon from "@mui/icons-material/ContactMail";
import CorporateFareIcon from "@mui/icons-material/CorporateFare";
import CurrencyExchangeIcon from "@mui/icons-material/CurrencyExchange";
import DescriptionIcon from "@mui/icons-material/Description";
import DesignServicesIcon from "@mui/icons-material/DesignServices";
import Diversity3Icon from "@mui/icons-material/Diversity3";
import EditNoteIcon from "@mui/icons-material/EditNote";
import EmailIcon from "@mui/icons-material/Email";
import EventAvailableIcon from "@mui/icons-material/EventAvailable";
import EventIcon from "@mui/icons-material/Event";
import FactCheckIcon from "@mui/icons-material/FactCheck";
import FlightIcon from "@mui/icons-material/Flight";
import FlightTakeoffIcon from "@mui/icons-material/FlightTakeoff";
import GavelIcon from "@mui/icons-material/Gavel";
import GroupsIcon from "@mui/icons-material/Groups";
import HandshakeIcon from "@mui/icons-material/Handshake";
import HomeWorkIcon from "@mui/icons-material/HomeWork";
import InsightsIcon from "@mui/icons-material/Insights";
import KeyboardIcon from "@mui/icons-material/Keyboard";
import LayersIcon from "@mui/icons-material/Layers";
import LinkIcon from "@mui/icons-material/Link";
import LocationCityIcon from "@mui/icons-material/LocationCity";
import MarkEmailReadIcon from "@mui/icons-material/MarkEmailRead";
import MenuBookIcon from "@mui/icons-material/MenuBook";
import NightsStayIcon from "@mui/icons-material/NightsStay";
import PaymentsIcon from "@mui/icons-material/Payments";
import PeopleIcon from "@mui/icons-material/People";
import PersonIcon from "@mui/icons-material/Person";
import PrecisionManufacturingIcon from "@mui/icons-material/PrecisionManufacturing";
import ReceiptLongIcon from "@mui/icons-material/ReceiptLong";
import RequestQuoteIcon from "@mui/icons-material/RequestQuote";
import RestartAltIcon from "@mui/icons-material/RestartAlt";
import RocketLaunchIcon from "@mui/icons-material/RocketLaunch";
import SavingsIcon from "@mui/icons-material/Savings";
import ScheduleIcon from "@mui/icons-material/Schedule";
import SearchIcon from "@mui/icons-material/Search";
import SecurityIcon from "@mui/icons-material/Security";
import SendIcon from "@mui/icons-material/Send";
import ShareIcon from "@mui/icons-material/Share";
import SlideshowIcon from "@mui/icons-material/Slideshow";
import StorageIcon from "@mui/icons-material/Storage";
import SummarizeIcon from "@mui/icons-material/Summarize";
import SupportAgentIcon from "@mui/icons-material/SupportAgent";
import SwapHorizIcon from "@mui/icons-material/SwapHoriz";
import SyncAltIcon from "@mui/icons-material/SyncAlt";
import TimerIcon from "@mui/icons-material/Timer";
import TravelExploreIcon from "@mui/icons-material/TravelExplore";
import TrendingUpIcon from "@mui/icons-material/TrendingUp";
import TuneIcon from "@mui/icons-material/Tune";
import VerifiedIcon from "@mui/icons-material/Verified";
import VerifiedUserIcon from "@mui/icons-material/VerifiedUser";
import VolunteerActivismIcon from "@mui/icons-material/VolunteerActivism";
import WebIcon from "@mui/icons-material/Web";
import WorkOffIcon from "@mui/icons-material/WorkOff";
import WorkspacePremiumIcon from "@mui/icons-material/WorkspacePremium";

export const ICONS = {
  AccessTimeFilledIcon,
  AccessTimeIcon,
  AccountBalanceIcon,
  AccountBalanceWalletIcon,
  AdsClickIcon,
  ArticleIcon,
  AssessmentIcon,
  AssignmentIcon,
  BarChartIcon,
  BuildIcon,
  BusinessIcon,
  CallIcon,
  CenterFocusStrongIcon,
  CheckCircleIcon,
  CleaningServicesIcon,
  CloudSyncIcon,
  CloudUploadIcon,
  ContactMailIcon,
  CorporateFareIcon,
  CurrencyExchangeIcon,
  DescriptionIcon,
  DesignServicesIcon,
  Diversity3Icon,
  EditNoteIcon,
  EmailIcon,
  EventAvailableIcon,
  EventIcon,
  FactCheckIcon,
  FlightIcon,
  FlightTakeoffIcon,
  GavelIcon,
  GroupsIcon,
  HandshakeIcon,
  HomeWorkIcon,
  InsightsIcon,
  KeyboardIcon,
  LayersIcon,
  LinkIcon,
  LocationCityIcon,
  MarkEmailReadIcon,
  MenuBookIcon,
  NightsStayIcon,
  PaymentsIcon,
  PeopleIcon,
  PersonIcon,
  PrecisionManufacturingIcon,
  ReceiptLongIcon,
  RequestQuoteIcon,
  RestartAltIcon,
  RocketLaunchIcon,
  SavingsIcon,
  ScheduleIcon,
  SearchIcon,
  SecurityIcon,
  SendIcon,
  ShareIcon,
  SlideshowIcon,
  StorageIcon,
  SummarizeIcon,
  SupportAgentIcon,
  SwapHorizIcon,
  SyncAltIcon,
  TimerIcon,
  TravelExploreIcon,
  TrendingUpIcon,
  TuneIcon,
  VerifiedIcon,
  VerifiedUserIcon,
  VolunteerActivismIcon,
  WebIcon,
  WorkOffIcon,
  WorkspacePremiumIcon,
};

// Accepts either a component (the pre-migration source files pass one directly)
// or a name (what the CMS stores). Returns null for anything unknown, so an
// unrecognised icon renders nothing instead of crashing the page — a missing
// 22px glyph is not worth a white screen.
export function resolveIcon(icon) {
  if (!icon) return null;
  if (typeof icon === "string") return ICONS[icon] ?? null;
  return icon;
}

export default ICONS;
