// The frozen per-service page template, applied on upload.
//
// Each service has a structure of its own — Bookkeeping is
// hero · intro · prose · whyEssential · solutions · cards · industries · faqs,
// Tax runs to nineteen sections — and those structures are what make a page look
// like the rest of its service rather than like whatever its last document
// happened to contain.
//
// The templates live one-per-service in db/templates/, linked by that folder's
// index.json, and are committed — so the shape of a page only changes when
// someone edits a template and reads the diff. Deriving them live would mean
// editing one page silently restructuring another.
//
// They are generated by scripts/gen-service-templates.mjs and split by
// scripts/split-service-templates.mjs. Edit db/templates/<service>.json to
// change one service's structure; regenerate only to re-derive all eight from
// the pages themselves.
//
// This module ensures a page HAS its service's sections. Filling them with the
// document is layoutMerge's job, which runs immediately after.

const path = require("path");

// One file per service, linked by db/templates/index.json.
//
// The eight templates used to share a single object, which meant every edit
// touched the same file and a diff never said which service had moved. Now
// "the Bookkeeping template" is a file you can open on its own, and choosing a
// service in the CMS selects exactly one of them.
//
// The old single blob is still read as a fallback, so a checkout that has not
// run scripts/split-service-templates.mjs keeps working rather than silently
// losing every template.
const TEMPLATE_DIR = path.join(__dirname, "../../db/templates");

const TEMPLATES = (() => {
  const out = {};

  try {
    // eslint-disable-next-line global-require, import/no-dynamic-require
    const index = require(path.join(TEMPLATE_DIR, "index.json"));
    for (const entry of index.templates || []) {
      try {
        // eslint-disable-next-line global-require, import/no-dynamic-require
        const template = require(path.join(TEMPLATE_DIR, entry.file));
        out[entry.service] = template;
      } catch {
        // One unreadable template must not take the other seven with it.
      }
    }
    if (Object.keys(out).length) return out;
  } catch {
    /* no split templates yet — fall through */
  }

  try {
    // eslint-disable-next-line global-require, import/no-dynamic-require
    return require(path.join(__dirname, "../../db/service-templates.json"));
  } catch {
    // Not generated yet. Every caller treats "no template" as "leave the page's
    // own structure alone", so the upload path keeps working.
    return {};
  }
})();

const templateFor = (service) => TEMPLATES[String(service || "").trim()] || null;

// Every service that has a template, for the CMS to offer and for a caller that
// wants to know what a service page will be shaped into before uploading to it.
const listTemplates = () =>
  Object.entries(TEMPLATES)
    .map(([service, t]) => ({
      service,
      sections: (t.sections || []).length,
      faqs: t.faqs || 0,
      // The shape a page of this service ends up with, in render order, so the
      // editor can show it rather than describing it.
      outline: (t.sections || []).map((s) => ({
        key: s.key,
        kind: s.kind,
        slots: s.slots || 1,
        heading: s.exampleHeading || "",
      })),
    }))
    .sort((a, b) => a.service.localeCompare(b.service));

const rendererOf = (g) => {
  if (!g || typeof g !== "object") return null;
  if (g.rows) return "table";
  if (g.paragraphs) return "prose";
  if (Array.isArray(g.items)) return typeof g.items[0] === "string" ? "checklist" : "cards";
  return null;
};

// An empty section of the shape the template calls for: the right renderer, the
// service's eyebrow and background, and the right number of slots — with the
// icons that service uses in that position already set.
function blankSection(section) {
  const node = { titleLead: "", highlight: "" };
  if (section.overline) node.overline = section.overline;
  if (section.bg) node.bg = section.bg;

  // The rest of the service's furniture. Without these a page built from a
  // document came out three cards across with no consultation button, while
  // every other page of its service is two across with one — the structure
  // matched and the page still did not look like its siblings.
  if (section.columns) node.columns = section.columns;
  if (section.ctaLabel) node.ctaLabel = section.ctaLabel;
  if (section.placement) node.placement = section.placement;

  const n = Math.max(1, section.slots || 1);
  if (section.kind === "prose") node.paragraphs = Array.from({ length: n }, () => "");
  else if (section.kind === "checklist") node.items = Array.from({ length: n }, () => "");
  else if (section.kind === "cards") {
    node.items = Array.from({ length: n }, (_, i) => ({
      icon: section.icons?.[i] || "",
      title: "",
      desc: "",
    }));
  } else if (section.kind === "table") {
    node.headers = ["", "", ""];
    node.rows = Array.from({ length: n }, () => ({ label: "", marks: [false, false] }));
  }
  return node;
}

// The page's own sections, flattened in render order so they can be matched
// against the template position by position.
function flatten(content) {
  const out = [];
  for (const [key, value] of Object.entries(content || {})) {
    if (key === "hero" || key === "faqs" || key === "faqsHeading" || key === "order") continue;
    const nodes = Array.isArray(value) ? value : [value];
    nodes.forEach((node) => {
      const kind = rendererOf(node);
      if (kind) out.push({ key, kind, node });
    });
  }
  return out;
}

/**
 * Give a page the sections its service template calls for.
 *
 * Existing content is never discarded: a template section the page already has
 * keeps its copy, and a section the page has that the template does not know
 * about is carried through rather than deleted.
 *
 * @returns {{ content: object, report: object }}
 */
function applyTemplate(content, service) {
  const template = templateFor(service);
  if (!template) {
    return { content: content || {}, report: { template: null, added: 0, matched: 0, extra: 0 } };
  }

  const existing = flatten(content);
  const used = new Set();
  // Do NOT invent an empty hero. CmsServicePage synthesises one from meta_title
  // when a page has none, and an empty object is truthy — adding it silently
  // defeated that and blanked the <h1> on the California page.
  const out = {};
  if (content && content.hero) out.hero = content.hero;

  let matched = 0;
  let added = 0;
  const groups = [];

  for (const section of template.sections) {
    // Reuse the page's own section for this position when it is the same shape.
    // "Reuse the existing relevant section wherever possible" — a page that
    // already has its whyEssential keeps that copy rather than being blanked.
    const at = existing.findIndex((e, i) => !used.has(i) && e.key === section.key && e.kind === section.kind)
      ?? -1;
    const fallback = at === -1
      ? existing.findIndex((e, i) => !used.has(i) && e.kind === section.kind)
      : -1;
    const idx = at !== -1 ? at : fallback;

    let node;
    if (idx !== -1) { used.add(idx); node = existing[idx].node; matched += 1; }
    else { node = blankSection(section); added += 1; }

    // The template decides presentation; a page that has drifted is brought back
    // into line without touching its words.
    if (section.overline && !node.overline) node.overline = section.overline;
    if (section.bg && !node.bg) node.bg = section.bg;

    if (section.key === "cardGroups") groups.push(node);
    else if (!(section.key in out)) out[section.key] = node;
    else groups.push(node);                     // a second `industries` has to be a card group
  }

  // A section `rendererOf` cannot classify is still content. The California
  // bookkeeping page has an `intro` carrying only `stats` — no paragraphs, no
  // items — so it never appeared in `flatten` and was dropped outright, taking
  // "100+ Clients / 10y+ Experience" with it. Anything unclassified is carried
  // through under its own key.
  for (const [key, value] of Object.entries(content || {})) {
    if (key === "hero" || key === "faqs" || key === "faqsHeading" || key === "order") continue;
    const nodes = Array.isArray(value) ? value : [value];
    if (!nodes.every((n) => rendererOf(n) === null)) continue;

    if (!(key in out)) { out[key] = value; continue; }

    // The template made a blank for this key, so skipping would still drop the
    // original's fields. Keep anything the blank does not define — `stats`,
    // `image`, `ctaLabel` — and let the template's own fields win where they
    // overlap.
    if (value && typeof value === "object" && !Array.isArray(value)) {
      out[key] = { ...value, ...out[key] };
    }
  }

  // Anything the page had that the template has no place for is kept, at the end,
  // rather than deleted. Losing copy to a template change would be the worst
  // possible failure here.
  const extra = existing.filter((_, i) => !used.has(i)).map((e) => e.node);
  const allGroups = [...groups, ...extra];
  if (allGroups.length) {
    allGroups.forEach((g, i) => { if (!g.bg) g.bg = i % 2 === 0 ? "default" : "paper"; });
    out.cardGroups = allGroups;
  }

  if (content?.faqs?.length) out.faqs = content.faqs;
  if (content?.faqsHeading) out.faqsHeading = content.faqsHeading;

  return {
    content: out,
    report: { template: template.service, sections: template.sections.length, matched, added, extra: extra.length },
  };
}

module.exports = { templateFor, listTemplates, applyTemplate, blankSection, rendererOf, TEMPLATES };
